return {
	
	APH_Hitbox_Name = "APH_Hitbox";
	clientAlpha = 0.18; -- 0.1 (smooth) a 0.4 (responsive), don't change it
	predictionTime = 0.18; -- in seconds
	customVehicleSeat = true;
	vehicleSeatName = "PilotSeat"; --[[
	only consider if customVehicleSeat = true
	]]
	--springBaseStiffness = 10;
	--springStiffnessVelocityScale = 0.1;
	suavizationFactor = 0.1; -- (higher values ??= less smoothness)
}